### ISSUE TITLE
create board inside github projects

### ISSUE THREAD

**Issue by RiskyFeryansyahP** [mqnoy/cookingman#11]
I think we need to consider to use Github Projects to create a board for ticket our task, so we will more knows about the task and flow every week. What do you think ? @mqnoy

**Comment by mqnoy** [comment]
@RiskyFeryansyahP Yes, to be more structured and more focused, thats good idea dude, 

Go ahead 😆

**Comment by RiskyFeryansyahP** [comment]
you or I will make a GitHub project? @mqnoy

**Comment by RiskyFeryansyahP** [comment]
> @RiskyFeryansyahP Yes, to be more structured and more focused, thats good idea dude,
> 
> Go ahead 😆

you or I will make a GitHub project? @mqnoy

**Comment by mqnoy** [comment]
@RiskyFeryansyahP  you can create ,if you want dude 😆, i will following

**Comment by RiskyFeryansyahP** [comment]
I close this issues @mqnoy
